"""
Generates `AppIcons.kt` from Material Symbols, so the app depends on no icon library at all.

    python composeApp/tools/gensymbols.py

Downloads one SVG per icon from google/material-design-icons and writes the path data into a Kotlin
file. Nothing is redrawn by hand and nothing is traced: the `d` attribute is copied verbatim and
parsed at runtime by Compose's own `PathParser`, which is the same parser that reads a vector
drawable. So what ships is exactly what Google drew.

## Why this replaced reading the library's sources jar

The previous generator lifted path data out of `material-icons-extended`'s sources jar, because at
the time thirteen icons still came from `material-icons-core` and two sources of truth risked two
slightly different drawings of the same glyph.

`material-icons-core` is gone now, and it took that argument with it. It also had to go further than
expected: the generated file used `materialIcon` and `materialPath`, which are *from* that library,
so dropping the dependency broke the twenty-four icons that had nothing to do with it. Everything is
built from `ImageVector.Builder` here instead, and the app has no icon dependency left.

## The 960 grid

Material Symbols ships on a 960x960 viewBox with a *negative* origin -- `0 -960 960 960` -- where
the old Material Icons used `0 0 24 24`. `ImageVector` has no viewport offset, so the path is
wrapped in a group translated down by 960. That is exact: no coordinate is rewritten, only moved.

## Adding one

Add a row to `WANTED` and re-run. `fill = 1` picks the filled variant, which is a different file
rather than a different attribute.
"""
import io
import os
import re
import urllib.request

OUT = "composeApp/src/commonMain/kotlin/com/bitsycore/cardbrowser/ui/common/AppIcons.kt"

BASE = "https://raw.githubusercontent.com/google/material-design-icons/master/symbols/web"

# (Kotlin name, Material Symbols name, fill, auto-mirror)
#
# Auto-mirroring is for the glyphs that point somewhere: they have to flip in a right-to-left
# layout, and `ImageVector` carries that as a flag rather than as a second drawing.
WANTED = [
	("ArrowBack", "arrow_back", 0, True),
	("ArrowDownward", "arrow_downward", 0, False),
	("ArrowDropDown", "arrow_drop_down", 0, False),
	("ArrowUpward", "arrow_upward", 0, False),
	("BrokenImage", "broken_image", 0, False),
	("Check", "check", 0, False),
	("CheckCircle", "check_circle", 0, False),
	("CheckCircleFilled", "check_circle", 1, False),
	("ChevronLeft", "chevron_left", 0, True),
	("ChevronRight", "chevron_right", 0, True),
	("CloudDownload", "cloud_download", 0, False),
	("CloudOff", "cloud_off", 0, False),
	("Close", "close", 0, False),
	("Delete", "delete", 0, False),
	("Description", "description", 0, False),
	("Download", "download", 0, False),
	("DownloadDone", "download_done", 0, False),
	("DragHandle", "drag_handle", 0, False),
	("ErrorOutline", "error", 0, False),
	("FilterList", "filter_list", 0, False),
	("GridView", "grid_view", 0, False),
	("Inbox", "inbox", 0, False),
	("KeyboardArrowRight", "keyboard_arrow_right", 0, True),
	("MoreVert", "more_vert", 0, False),
	("OpenInNew", "open_in_new", 0, True),
	("Refresh", "refresh", 0, False),
	("Search", "search", 0, False),
	("SearchOff", "search_off", 0, False),
	("StarBorder", "star", 0, False),
	("StarFilled", "star", 1, False),
	("Storage", "storage", 0, False),
	("Style", "style", 0, False),
	("TravelExplore", "travel_explore", 0, False),
	("Tune", "tune", 0, False),
	("Visibility", "visibility", 0, False),
	("VisibilityOff", "visibility_off", 0, False),
]

HEADER = '''package com.bitsycore.cardbrowser.ui.common

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

/**
 * Every icon this app draws.
 *
 * **Generated by `composeApp/tools/gensymbols.py`. Do not edit.**
 *
 * ## Why the app has no icon dependency
 *
 * `material-icons-extended` is every Material icon there is -- a 36 MB desktop jar and an 18 MB
 * klib per iOS target -- for the handful this app draws. R8 strips the rest from an Android release
 * build; nothing strips them from a desktop distributable or an iOS binary.
 *
 * `material-icons-core` was smaller and was dropped for a different reason: it publishes no klibs
 * for the native desktop targets, so it blocked the Kotlin/Native port for a dozen glyphs. See
 * `docs/NATIVE_DESKTOP.md`.
 *
 * ## Where these come from
 *
 * Material Symbols, downloaded from google/material-design-icons. The `d` attribute of each SVG is
 * copied verbatim and parsed at runtime by Compose's own `PathParser` -- the same parser that reads
 * a vector drawable -- so these are Google's drawings rather than anyone's tracing of them.
 *
 * Apache 2.0, (c) Google.
 */
object AppIcons {
'''

FOOTER = '''}

/**
 * One Material Symbol, built from its SVG path.
 *
 * The group exists to move the drawing onto the canvas. Material Symbols uses a `0 -960 960 960`
 * viewBox -- a 960 grid whose origin is at the *bottom* -- and `ImageVector` has no viewport offset,
 * so the path is translated down by a full grid instead. Nothing is rescaled: the viewport is
 * declared as 960 and the 24dp default size does the scaling, exactly as the source SVG's own
 * `width="24"` does.
 *
 * Parsed once and held by the `by lazy` on each property above, so an icon costs its parse the
 * first time it is drawn and nothing after that.
 */
private fun symbol(name: String, pathData: String, autoMirror: Boolean = false): ImageVector =
	ImageVector.Builder(
		name = "AppIcons.$name",
		defaultWidth = ICON_SIZE,
		defaultHeight = ICON_SIZE,
		viewportWidth = SYMBOL_GRID,
		viewportHeight = SYMBOL_GRID,
		autoMirror = autoMirror,
	)
		.addGroup(translationY = SYMBOL_GRID)
		.addPath(
			pathData = PathParser().parsePathString(pathData).toNodes(),
			// Black, and then tinted by whatever draws it. `Icon` applies `LocalContentColor` over
			// the top, which is how every one of these follows the theme without knowing about it.
			fill = SolidColor(Color.Black),
		)
		.clearGroup()
		.build()

/** The size every Material icon is drawn at, and what the source SVGs declare. */
private val ICON_SIZE = 24.dp

/** Material Symbols' viewBox. See [symbol] for why the origin needs a translation. */
private const val SYMBOL_GRID = 960f
'''


def fetch(symbol, fill):
	"""The `d` attribute of one Material Symbol, verbatim."""
	vVariant = "materialsymbolsoutlined"
	vName = "%s_%s24px.svg" % (symbol, "fill1_" if fill else "")
	vUrl = "%s/%s/%s/%s" % (BASE, symbol, vVariant, vName)
	with urllib.request.urlopen(vUrl, timeout=30) as vResponse:
		vSvg = vResponse.read().decode("utf-8")
	vPaths = re.findall(r'<path[^>]*\sd="([^"]+)"', vSvg)
	if len(vPaths) != 1:
		raise SystemExit("%s: expected one path, found %d" % (vUrl, len(vPaths)))
	return vPaths[0]


def main():
	if not os.path.isdir("composeApp"):
		raise SystemExit("run from the repository root")
	vOut = [HEADER]
	for vName, vSymbol, vFill, vMirror in WANTED:
		vPath = fetch(vSymbol, vFill)
		vMirrorArg = ", autoMirror = true" if vMirror else ""
		vOut.append(
			'\tval %s: ImageVector by lazy { symbol("%s", "%s"%s) }\n'
			% (vName, vName, vPath, vMirrorArg),
		)
	vOut.append(FOOTER)
	io.open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(vOut))
	print("wrote %s: %d icons" % (OUT, len(WANTED)))


if __name__ == "__main__":
	main()
