package com.bitsycore.cardbrowser.ui.common

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

/**
 * Every icon this app draws.
 *
 * **Generated by `composeApp/tools/gensymbols.py`. Do not edit.**
 *
 * ## Why the app has no icon dependency
 *
 * `material-icons-extended` is every Material icon there is -- a 36 MB desktop jar and an 18 MB
 * klib per iOS target -- for the handful this app draws. R8 strips the rest from an Android release
 * build; nothing strips them from a desktop distributable or an iOS binary.
 *
 * `material-icons-core` was smaller and was dropped for a different reason: it publishes no klibs
 * for the native desktop targets, so it blocked the Kotlin/Native port for a dozen glyphs. See
 * `docs/NATIVE_DESKTOP.md`.
 *
 * ## Where these come from
 *
 * Material Symbols, downloaded from google/material-design-icons. The `d` attribute of each SVG is
 * copied verbatim and parsed at runtime by Compose's own `PathParser` -- the same parser that reads
 * a vector drawable -- so these are Google's drawings rather than anyone's tracing of them.
 *
 * Apache 2.0, (c) Google.
 */
object AppIcons {

	val ArrowBack: ImageVector by lazy { symbol("ArrowBack", "m313-440 224 224-57 56-320-320 320-320 57 56-224 224h487v80H313Z", autoMirror = true) }

	val ArrowDownward: ImageVector by lazy { symbol("ArrowDownward", "M440-800v487L216-537l-56 57 320 320 320-320-56-57-224 224v-487h-80Z") }

	val ArrowDropDown: ImageVector by lazy { symbol("ArrowDropDown", "M480-360 280-560h400L480-360Z") }

	val ArrowUpward: ImageVector by lazy { symbol("ArrowUpward", "M440-160v-487L216-423l-56-57 320-320 320 320-56 57-224-224v487h-80Z") }

	val BrokenImage: ImageVector by lazy { symbol("BrokenImage", "M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm40-337 160-160 160 160 160-160 40 40v-183H200v263l40 40Zm-40 257h560v-264l-40-40-160 160-160-160-160 160-40-40v184Zm0 0v-264 80-376 560Z") }

	val Check: ImageVector by lazy { symbol("Check", "M382-240 154-468l57-57 171 171 367-367 57 57-424 424Z") }

	val CheckCircle: ImageVector by lazy { symbol("CheckCircle", "m424-296 282-282-56-56-226 226-114-114-56 56 170 170Zm56 216q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Zm0-80q134 0 227-93t93-227q0-134-93-227t-227-93q-134 0-227 93t-93 227q0 134 93 227t227 93Zm0-320Z") }

	val CheckCircleFilled: ImageVector by lazy { symbol("CheckCircleFilled", "m424-296 282-282-56-56-226 226-114-114-56 56 170 170Zm56 216q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Z") }

	val ChevronLeft: ImageVector by lazy { symbol("ChevronLeft", "M560-240 320-480l240-240 56 56-184 184 184 184-56 56Z", autoMirror = true) }

	val ChevronRight: ImageVector by lazy { symbol("ChevronRight", "M504-480 320-664l56-56 240 240-240 240-56-56 184-184Z", autoMirror = true) }

	val CloudDownload: ImageVector by lazy { symbol("CloudDownload", "M260-160q-91 0-155.5-63T40-377q0-78 47-139t123-78q17-72 85-137t145-65q33 0 56.5 23.5T520-716v242l64-62 56 56-160 160-160-160 56-56 64 62v-242q-76 14-118 73.5T280-520h-20q-58 0-99 41t-41 99q0 58 41 99t99 41h480q42 0 71-29t29-71q0-42-29-71t-71-29h-60v-80q0-48-22-89.5T600-680v-93q74 35 117 103.5T760-520q69 8 114.5 59.5T920-340q0 75-52.5 127.5T740-160H260Zm220-358Z") }

	val CloudOff: ImageVector by lazy { symbol("CloudOff", "M792-56 686-160H260q-92 0-156-64T40-380q0-77 47.5-137T210-594q3-8 6-15.5t6-16.5L56-792l56-56 736 736-56 56ZM260-240h346L284-562q-2 11-3 21t-1 21h-20q-58 0-99 41t-41 99q0 58 41 99t99 41Zm185-161Zm419 191-58-56q17-14 25.5-32.5T840-340q0-42-29-71t-71-29h-60v-80q0-83-58.5-141.5T480-720q-27 0-52 6.5T380-693l-58-58q35-24 74.5-36.5T480-800q117 0 198.5 81.5T760-520q69 8 114.5 59.5T920-340q0 39-15 72.5T864-210ZM593-479Z") }

	val Close: ImageVector by lazy { symbol("Close", "m256-200-56-56 224-224-224-224 56-56 224 224 224-224 56 56-224 224 224 224-56 56-224-224-224 224Z") }

	val Delete: ImageVector by lazy { symbol("Delete", "M280-120q-33 0-56.5-23.5T200-200v-520h-40v-80h200v-40h240v40h200v80h-40v520q0 33-23.5 56.5T680-120H280Zm400-600H280v520h400v-520ZM360-280h80v-360h-80v360Zm160 0h80v-360h-80v360ZM280-720v520-520Z") }

	val Description: ImageVector by lazy { symbol("Description", "M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z") }

	val Download: ImageVector by lazy { symbol("Download", "M480-320 280-520l56-58 104 104v-326h80v326l104-104 56 58-200 200ZM240-160q-33 0-56.5-23.5T160-240v-120h80v120h480v-120h80v120q0 33-23.5 56.5T720-160H240Z") }

	val DownloadDone: ImageVector by lazy { symbol("DownloadDone", "M382-320 155-547l57-57 170 170 366-366 57 57-423 423ZM200-160v-80h560v80H200Z") }

	val DragHandle: ImageVector by lazy { symbol("DragHandle", "M160-360v-80h640v80H160Zm0-160v-80h640v80H160Z") }

	val ErrorOutline: ImageVector by lazy { symbol("ErrorOutline", "M480-280q17 0 28.5-11.5T520-320q0-17-11.5-28.5T480-360q-17 0-28.5 11.5T440-320q0 17 11.5 28.5T480-280Zm-40-160h80v-240h-80v240Zm40 360q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q83 0 156 31.5T763-763q54 54 85.5 127T880-480q0 83-31.5 156T763-197q-54 54-127 85.5T480-80Zm0-80q134 0 227-93t93-227q0-134-93-227t-227-93q-134 0-227 93t-93 227q0 134 93 227t227 93Zm0-320Z") }

	val FilterList: ImageVector by lazy { symbol("FilterList", "M400-240v-80h160v80H400ZM240-440v-80h480v80H240ZM120-640v-80h720v80H120Z") }

	val GridView: ImageVector by lazy { symbol("GridView", "M120-520v-320h320v320H120Zm0 400v-320h320v320H120Zm400-400v-320h320v320H520Zm0 400v-320h320v320H520ZM200-600h160v-160H200v160Zm400 0h160v-160H600v160Zm0 400h160v-160H600v160Zm-400 0h160v-160H200v160Zm400-400Zm0 240Zm-240 0Zm0-240Z") }

	val Inbox: ImageVector by lazy { symbol("Inbox", "M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h560q33 0 56.5 23.5T840-760v560q0 33-23.5 56.5T760-120H200Zm0-80h560v-120H640q-30 38-71.5 59T480-240q-47 0-88.5-21T320-320H200v120Zm280-120q38 0 69-22t43-58h168v-360H200v360h168q12 36 43 58t69 22ZM200-200h560-560Z") }

	val KeyboardArrowRight: ImageVector by lazy { symbol("KeyboardArrowRight", "M504-480 320-664l56-56 240 240-240 240-56-56 184-184Z", autoMirror = true) }

	val MoreVert: ImageVector by lazy { symbol("MoreVert", "M480-160q-33 0-56.5-23.5T400-240q0-33 23.5-56.5T480-320q33 0 56.5 23.5T560-240q0 33-23.5 56.5T480-160Zm0-240q-33 0-56.5-23.5T400-480q0-33 23.5-56.5T480-560q33 0 56.5 23.5T560-480q0 33-23.5 56.5T480-400Zm0-240q-33 0-56.5-23.5T400-720q0-33 23.5-56.5T480-800q33 0 56.5 23.5T560-720q0 33-23.5 56.5T480-640Z") }

	val OpenInNew: ImageVector by lazy { symbol("OpenInNew", "M200-120q-33 0-56.5-23.5T120-200v-560q0-33 23.5-56.5T200-840h280v80H200v560h560v-280h80v280q0 33-23.5 56.5T760-120H200Zm188-212-56-56 372-372H560v-80h280v280h-80v-144L388-332Z", autoMirror = true) }

	val Refresh: ImageVector by lazy { symbol("Refresh", "M480-160q-134 0-227-93t-93-227q0-134 93-227t227-93q69 0 132 28.5T720-690v-110h80v280H520v-80h168q-32-56-87.5-88T480-720q-100 0-170 70t-70 170q0 100 70 170t170 70q77 0 139-44t87-116h84q-28 106-114 173t-196 67Z") }

	val Search: ImageVector by lazy { symbol("Search", "M784-120 532-372q-30 24-69 38t-83 14q-109 0-184.5-75.5T120-580q0-109 75.5-184.5T380-840q109 0 184.5 75.5T640-580q0 44-14 83t-38 69l252 252-56 56ZM380-400q75 0 127.5-52.5T560-580q0-75-52.5-127.5T380-760q-75 0-127.5 52.5T200-580q0 75 52.5 127.5T380-400Z") }

	val SearchOff: ImageVector by lazy { symbol("SearchOff", "M280-80q-83 0-141.5-58.5T80-280q0-83 58.5-141.5T280-480q83 0 141.5 58.5T480-280q0 83-58.5 141.5T280-80Zm544-40L568-376q-12-13-25.5-26.5T516-428q38-24 61-64t23-88q0-75-52.5-127.5T420-760q-75 0-127.5 52.5T240-580q0 6 .5 11.5T242-557q-18 2-39.5 8T164-535q-2-11-3-22t-1-23q0-109 75.5-184.5T420-840q109 0 184.5 75.5T680-580q0 43-13.5 81.5T629-428l251 252-56 56Zm-615-61 71-71 70 71 29-28-71-71 71-71-28-28-71 71-71-71-28 28 71 71-71 71 28 28Z") }

	val StarBorder: ImageVector by lazy { symbol("StarBorder", "m354-287 126-76 126 77-33-144 111-96-146-13-58-136-58 135-146 13 111 97-33 143ZM233-120l65-281L80-590l288-25 112-265 112 265 288 25-218 189 65 281-247-149-247 149Zm247-350Z") }

	val StarFilled: ImageVector by lazy { symbol("StarFilled", "m233-120 65-281L80-590l288-25 112-265 112 265 288 25-218 189 65 281-247-149-247 149Z") }

	val Storage: ImageVector by lazy { symbol("Storage", "M120-160v-160h720v160H120Zm80-40h80v-80h-80v80Zm-80-440v-160h720v160H120Zm80-40h80v-80h-80v80Zm-80 280v-160h720v160H120Zm80-40h80v-80h-80v80Z") }

	val Style: ImageVector by lazy { symbol("Style", "m159-168-34-14q-31-13-41.5-45t3.5-63l72-156v278Zm160 88q-33 0-56.5-23.5T239-160v-240l106 294q3 7 6 13.5t8 12.5h-40Zm206-4q-32 12-62-3t-42-47L243-622q-12-32 2-62.5t46-41.5l302-110q32-12 62 3t42 47l178 488q12 32-2 62.5T827-194L525-84Zm-86-476q17 0 28.5-11.5T479-600q0-17-11.5-28.5T439-640q-17 0-28.5 11.5T399-600q0 17 11.5 28.5T439-560Zm58 400 302-110-178-490-302 110 178 490ZM319-650l302-110-302 110Z") }

	val TravelExplore: ImageVector by lazy { symbol("TravelExplore", "M480-80q-83 0-156-31.5T197-197q-54-54-85.5-127T80-480q0-83 31.5-156T197-763q54-54 127-85.5T480-880q146 0 255.5 91.5T872-559h-82q-19-73-68.5-130.5T600-776v16q0 33-23.5 56.5T520-680h-80v80q0 17-11.5 28.5T400-560h-80v80h80v120h-40L168-552q-3 18-5.5 36t-2.5 36q0 131 92 225t228 95v80Zm364-20L716-228q-21 12-45 20t-51 8q-75 0-127.5-52.5T440-380q0-75 52.5-127.5T620-560q75 0 127.5 52.5T800-380q0 27-8 51t-20 45l128 128-56 56ZM620-280q42 0 71-29t29-71q0-42-29-71t-71-29q-42 0-71 29t-29 71q0 42 29 71t71 29Z") }

	val Tune: ImageVector by lazy { symbol("Tune", "M440-120v-240h80v80h320v80H520v80h-80Zm-320-80v-80h240v80H120Zm160-160v-80H120v-80h160v-80h80v240h-80Zm160-80v-80h400v80H440Zm160-160v-240h80v80h160v80H680v80h-80Zm-480-80v-80h400v80H120Z") }

	val Visibility: ImageVector by lazy { symbol("Visibility", "M480-320q75 0 127.5-52.5T660-500q0-75-52.5-127.5T480-680q-75 0-127.5 52.5T300-500q0 75 52.5 127.5T480-320Zm0-72q-45 0-76.5-31.5T372-500q0-45 31.5-76.5T480-608q45 0 76.5 31.5T588-500q0 45-31.5 76.5T480-392Zm0 192q-146 0-266-81.5T40-500q54-137 174-218.5T480-800q146 0 266 81.5T920-500q-54 137-174 218.5T480-200Zm0-300Zm0 220q113 0 207.5-59.5T832-500q-50-101-144.5-160.5T480-720q-113 0-207.5 59.5T128-500q50 101 144.5 160.5T480-280Z") }

	val VisibilityOff: ImageVector by lazy { symbol("VisibilityOff", "m644-428-58-58q9-47-27-88t-93-32l-58-58q17-8 34.5-12t37.5-4q75 0 127.5 52.5T660-500q0 20-4 37.5T644-428Zm128 126-58-56q38-29 67.5-63.5T832-500q-50-101-143.5-160.5T480-720q-29 0-57 4t-55 12l-62-62q41-17 84-25.5t90-8.5q151 0 269 83.5T920-500q-23 59-60.5 109.5T772-302Zm20 246L624-222q-35 11-70.5 16.5T480-200q-151 0-269-83.5T40-500q21-53 53-98.5t73-81.5L56-792l56-56 736 736-56 56ZM222-624q-29 26-53 57t-41 67q50 101 143.5 160.5T480-280q20 0 39-2.5t39-5.5l-36-38q-11 3-21 4.5t-21 1.5q-75 0-127.5-52.5T300-500q0-11 1.5-21t4.5-21l-84-82Zm319 93Zm-151 75Z") }

}

/**
 * One Material Symbol, built from its SVG path.
 *
 * The group exists to move the drawing onto the canvas. Material Symbols uses a `0 -960 960 960`
 * viewBox -- a 960 grid whose origin is at the *bottom* -- and `ImageVector` has no viewport offset,
 * so the path is translated down by a full grid instead. Nothing is rescaled: the viewport is
 * declared as 960 and the 24dp default size does the scaling, exactly as the source SVG's own
 * `width="24"` does.
 *
 * Parsed once and held by the `by lazy` on each property above, so an icon costs its parse the
 * first time it is drawn and nothing after that.
 */
private fun symbol(name: String, pathData: String, autoMirror: Boolean = false): ImageVector =
	ImageVector.Builder(
		name = "AppIcons.$name",
		defaultWidth = ICON_SIZE,
		defaultHeight = ICON_SIZE,
		viewportWidth = SYMBOL_GRID,
		viewportHeight = SYMBOL_GRID,
		autoMirror = autoMirror,
	)
		.addGroup(translationY = SYMBOL_GRID)
		.addPath(
			pathData = PathParser().parsePathString(pathData).toNodes(),
			// Black, and then tinted by whatever draws it. `Icon` applies `LocalContentColor` over
			// the top, which is how every one of these follows the theme without knowing about it.
			fill = SolidColor(Color.Black),
		)
		.clearGroup()
		.build()

/** The size every Material icon is drawn at, and what the source SVGs declare. */
private val ICON_SIZE = 24.dp

/** Material Symbols' viewBox. See [symbol] for why the origin needs a translation. */
private const val SYMBOL_GRID = 960f
